import Head from "next/head";
import SubmitDesign from "~/components/SubmitDesign";
import UploadDesign from "~/components/UploadDesign";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-5 flex items-center justify-center">
          Logo goes here
        </div>
        <UploadDesign />
        <SubmitDesign />
      </main>
    </>
  );
}
